// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zerbitzaria.Data;

#nullable disable

namespace Zerbitzaria.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260209085537_SyncTradesSchema")]
    partial class SyncTradesSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Zerbitzaria.Models.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Change")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsUp")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Markets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Change = 2.1000000000000001,
                            IsUp = true,
                            Price = 42123.45m,
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = 2,
                            Change = 1.8,
                            IsUp = true,
                            Price = 3210.12m,
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = 3,
                            Change = -0.5,
                            IsUp = false,
                            Price = 98.45m,
                            Symbol = "SOL"
                        },
                        new
                        {
                            Id = 4,
                            Change = 0.90000000000000002,
                            IsUp = true,
                            Price = 0.78m,
                            Symbol = "XRP"
                        });
                });

            modelBuilder.Entity("Zerbitzaria.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leverage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Margin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntryPrice = 0m,
                            IsOpen = true,
                            Leverage = 63,
                            Margin = 12m,
                            Quantity = 0m,
                            Side = "LONG",
                            Symbol = "DOGE",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Zerbitzaria.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leverage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Margin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pnl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntryPrice = 42123.45m,
                            IsOpen = false,
                            Leverage = 1,
                            Margin = 100m,
                            Pnl = 1771827.25m,
                            Quantity = 100m,
                            Side = "LONG",
                            Symbol = "BTCUSD",
                            Timestamp = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Zerbitzaria.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 100000m,
                            PasswordHash = "$2a$11$xc.smXeoQAItIhi8v.oh8efTbcXepiDZ8vt5cTdl.OLPKij23ZCNa",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
