name: tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore TradePro.sln
      - name: Build
        run: dotnet build TradePro.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test TradePro.sln --configuration Release --no-build
